### PR TITLE
Fix filesystem fallback

### PR DESCRIPTION
**Pull request by ThrawnCA**
Filesystem fallback was broken by 1a4944c4c36b65550e2e52452182503252d5e2ff (because changing from direct access to redirect meant that we would never detect the missing file). This fixes it by requesting the file metadata before redirecting.

### CODE REVIEW

**Comment by bstutsky** [comment]
Firstly, thanks for contributing.

**Comment by bstutsky** [comment]
I need to get some feedback before I can review this, I'm not sure when that will be.

**Comment by bstutsky** [comment]
Can you add some testable steps for each of the changes made? It will make it easier to review this when I get to it.

**Comment by ThrawnCA** [comment]
The only change that really matters is 00c3240; feel free to cherry-pick that one if you're concerned about the typo fixes.

Testing it is pretty easy; the fallback feature is completely non-functional ever since 1a4944c happened.

- Upload a file without ckanext-s3filestore enabled.
- Set `ckanext.s3filestore.filesystem_download_fallback = true`.
- Enable ckanext-s3filestore version 0.1.1.
- Browse to the uploaded resource and try to download the file. You'll end up at an S3 URL with a "no such key" error.
- Update ckanext-s3filestore to 00c3240 and restart CKAN.
- Attempt to download the resource again. You should end up at an "/fs_download/" URL and successfully download the file.

**Comment by ThrawnCA** [comment]
OK, there's an additional commit on our branch (and thus now included in this pull request). It's just copying some useful behavior (detecting the uploaded file size) from the standard filestore uploader, so it should be harmless, but feel free to just cherry-pick what you want if it's a concern.

**Comment by ThrawnCA** [comment]
Bump.

Is there any further information we can give that would be helpful in testing this? We've been using it for months now on www.data.qld.gov.au and www.publications.qld.gov.au and it's working quite smoothly.

**Comment by ThrawnCA** [comment]
Bump. There are further enhancements in our fork, if you're interested, like updating everything to Boto3 and ditching the old boto, but it's getting harder to pull the changes out into separate pull requests.

**Comment by bstutsky** [comment]
@ThrawnCA Hey, sorry I didn't get back to you until now. I'm glad to see you're still improving on this. I'm not going to be maintaining this repo. I think you should fork and own this :)

**Comment by ThrawnCA** [comment]
@bstutsky Thanks for the feedback. We've been working with the keitaroinc fork, which is also being maintained, and will probably sort out ownership once we've merged the two codebases.

**Pull request closed without merging**
